In [ ]:
# Bismillah

In [1]:
print('Hellow')

Hellow

In [2]:
import numpy as np
import pandas as pd
import datetime as dt
# from datetime import datetime
import matplotlib.pyplot as plt
%matplotlib inline
pd.set_option('precision', 7)
from pandas_datareader import data as web

In [3]:
msft = web.DataReader('MSFT', 'yahoo', '2012-01-01', '2013-12-30')
msft

# collects the data from yahoo finance for Microsoft for the said period and stores it in data frame, msft.

,High,Low,Open,Close,Volume,Adj Close
Date,,,,,,
2012-01-03,26.9599991,26.3899994,26.5499992,26.7700005,64731500.0,21.6231270
2012-01-04,27.4699993,26.7800007,26.8199997,27.3999996,80516100.0,22.1320133
2012-01-05,27.7299995,27.2900009,27.3799992,27.6800003,56081400.0,22.3581715
2012-01-06,28.1900005,27.5300007,27.5300007,28.1100006,99455500.0,22.7055016
2012-01-09,28.1000004,27.7199993,28.0499992,27.7399998,59706800.0,22.4066410
...,...,...,...,...,...,...
2013-12-23,36.8899994,36.5499992,36.8100014,36.6199989,25128700.0,31.3362293
2013-12-24,37.1699982,36.6399994,36.7200012,37.0800018,14243000.0,31.7298641
2013-12-26,37.4900017,37.1699982,37.2000008,37.4399986,17612800.0,32.0379219
2013-12-27,37.6199989,37.1699982,37.5800018,37.2900009,14563000.0,31.9095688
2013-12-30,37.3800011,36.9000015,37.2200012,37.2900009,16290500.0,31.9095688

### Shifting and lagging time-series data:

In [4]:
msftAC = msft['Adj Close']
msftAC

# select only 'Adj Close' column from the msft data frame, and store it in a series, msftAC.

Date
2012-01-03    21.6231270
2012-01-04    22.1320133
2012-01-05    22.3581715
2012-01-06    22.7055016
2012-01-09    22.4066410
                 ...
2013-12-23    31.3362293
2013-12-24    31.7298641
2013-12-26    32.0379219
2013-12-27    31.9095688
2013-12-30    31.9095688
Name: Adj Close, Length: 501, dtype: float64

In [5]:
type(msftAC)

# msftAC is a series. We can convert it to a data frame by typing: msftAC = msft[['Adj Close']]

pandas.core.series.Series

In [6]:
shift_forward = msftAC.shift(1)
msftAC.head(), shift_forward.head()
# This will shift the prices one day forward.
# results in one NaN value at the start since there was no value prior to be shifted to 2012-01-03.
# the number of NaN values will depend on the number of indices we are shifting forward or backward. For instance, the index is 
# daily dates, so if we shift one day forward, it means we are forwarding one index resulting into one NaN value. If we would 
# shift 2 days forward, it means we are forwarding two indices resulting into two NaN values.

(Date
 2012-01-03    21.6231270
 2012-01-04    22.1320133
 2012-01-05    22.3581715
 2012-01-06    22.7055016
 2012-01-09    22.4066410
 Name: Adj Close, dtype: float64,
 Date
 2012-01-03           NaN
 2012-01-04    21.6231270
 2012-01-05    22.1320133
 2012-01-06    22.3581715
 2012-01-09    22.7055016
 Name: Adj Close, dtype: float64)

In [7]:
msftAC.tail(), shift_forward.tail()
# the last price 31.9755402 on date 2013-12-30 in msftAC has been lost away in shift_forward since there is no index available for
# it now after the prices have been shifted one day forward. So, we got one NaN value at the start and one value lost at the end
# by shifting one day forward.

(Date
 2013-12-23    31.3362293
 2013-12-24    31.7298641
 2013-12-26    32.0379219
 2013-12-27    31.9095688
 2013-12-30    31.9095688
 Name: Adj Close, dtype: float64,
 Date
 2013-12-23    31.4902611
 2013-12-24    31.3362293
 2013-12-26    31.7298641
 2013-12-27    32.0379219
 2013-12-30    31.9095688
 Name: Adj Close, dtype: float64)

In [8]:
shift_backward = msftAC.shift(-2)
# will shift two days (two indices) backward.

In [9]:
msftAC, shift_backward
# inserts two NaNs at the end since we have shifted two days (two indices) backward and the first two values lost since there are 
# no indices available for them.

(Date
 2012-01-03    21.6231270
 2012-01-04    22.1320133
 2012-01-05    22.3581715
 2012-01-06    22.7055016
 2012-01-09    22.4066410
                  ...
 2013-12-23    31.3362293
 2013-12-24    31.7298641
 2013-12-26    32.0379219
 2013-12-27    31.9095688
 2013-12-30    31.9095688
 Name: Adj Close, Length: 501, dtype: float64,
 Date
 2012-01-03    22.3581715
 2012-01-04    22.7055016
 2012-01-05    22.4066410
 2012-01-06    22.4874191
 2012-01-09    22.3904877
                  ...
 2013-12-23    32.0379219
 2013-12-24    31.9095688
 2013-12-26    31.9095688
 2013-12-27           NaN
 2013-12-30           NaN
 Name: Adj Close, Length: 501, dtype: float64)

In [10]:
shift_1sec = msftAC.shift(1, freq = 'S')

In [11]:
msftAC, shift_1sec
# the prices have been shifted just one second forward each day. That means that the prices still exist on the same date. So, no
# value is lost and no NaN is inserted.
# the frequency could be changed to any desirable level such as hour etc.
# Note that the index labels have been adjusted according to the specified frequency resulting into a new dataframe or series in 
# this case.

(Date
 2012-01-03    21.6231270
 2012-01-04    22.1320133
 2012-01-05    22.3581715
 2012-01-06    22.7055016
 2012-01-09    22.4066410
                  ...
 2013-12-23    31.3362293
 2013-12-24    31.7298641
 2013-12-26    32.0379219
 2013-12-27    31.9095688
 2013-12-30    31.9095688
 Name: Adj Close, Length: 501, dtype: float64,
 Date
 2012-01-03 00:00:01    21.6231270
 2012-01-04 00:00:01    22.1320133
 2012-01-05 00:00:01    22.3581715
 2012-01-06 00:00:01    22.7055016
 2012-01-09 00:00:01    22.4066410
                           ...
 2013-12-23 00:00:01    31.3362293
 2013-12-24 00:00:01    31.7298641
 2013-12-26 00:00:01    32.0379219
 2013-12-27 00:00:01    31.9095688
 2013-12-30 00:00:01    31.9095688
 Name: Adj Close, Length: 501, dtype: float64)

In [12]:
shift_1sec['2012-01-03':'2012-01-06']
# note that the indices now include the time as well in addition to the date.

Date
2012-01-03 00:00:01    21.6231270
2012-01-04 00:00:01    22.1320133
2012-01-05 00:00:01    22.3581715
2012-01-06 00:00:01    22.7055016
Name: Adj Close, dtype: float64

### Practical Example:

In [13]:
msftAC, msftAC.shift(1)
# the prices have been shifted one day forward.

(Date
 2012-01-03    21.6231270
 2012-01-04    22.1320133
 2012-01-05    22.3581715
 2012-01-06    22.7055016
 2012-01-09    22.4066410
                  ...
 2013-12-23    31.3362293
 2013-12-24    31.7298641
 2013-12-26    32.0379219
 2013-12-27    31.9095688
 2013-12-30    31.9095688
 Name: Adj Close, Length: 501, dtype: float64,
 Date
 2012-01-03           NaN
 2012-01-04    21.6231270
 2012-01-05    22.1320133
 2012-01-06    22.3581715
 2012-01-09    22.7055016
                  ...
 2013-12-23    31.4902611
 2013-12-24    31.3362293
 2013-12-26    31.7298641
 2013-12-27    32.0379219
 2013-12-30    31.9095688
 Name: Adj Close, Length: 501, dtype: float64)

In [14]:
msftAC/msftAC

Date
2012-01-03    1.0
2012-01-04    1.0
2012-01-05    1.0
2012-01-06    1.0
2012-01-09    1.0
             ...
2013-12-23    1.0
2013-12-24    1.0
2013-12-26    1.0
2013-12-27    1.0
2013-12-30    1.0
Name: Adj Close, Length: 501, dtype: float64

In [15]:
msftAC / msftAC.shift(1)
# the dividsion is based on the same index labels. That is, the price on 2012-01-04 in msftAC is divided the price on 2012-01-04 in
# msftAC.shift(1). This is equal t`o (current price divided by previous price). The previous price is the amount invested.

# Interpretation: the $1 invested has grown to $1.0235337. So, the net return is $1.0235337 - 1 = $0.0235337. That is why we need
# to subtract 1 as shown below.
# the first value is NaN because value is missing in msftAC.shift(1) on 2012-01-03.
# the last value is 1.00000 because in both msftAC and msftAC.shift(1) the value on 2013-12-30 is the same.

# Very important to note that we CANNOT say that $1 investment at the start (2012-01-03) has grown to (or in this case 
# has remained same) to $1 at the end of the period (2013-12-30) since we can see that the adj close price at the start
# is $21.62 and at the end is $31.90. So, there is definately a gain. But then why we have 1 at the end of the output of
# this cell? It is because these returns are computed on daily basis. So, this 1 shows that $1 dollar invested on 2013-12
#-27 has remained same $1 and it makes sense since the price has remained unchanged from 2013-12-27 to 2013-12-30. To find
# the total return, we need to find the cumulative product.

Date
2012-01-03          NaN
2012-01-04    1.0235344
2012-01-05    1.0102186
2012-01-06    1.0155348
2012-01-09    0.9868375
                ...
2013-12-23    0.9951086
2013-12-24    1.0125617
2013-12-26    1.0097088
2013-12-27    0.9959937
2013-12-30    1.0000000
Name: Adj Close, Length: 501, dtype: float64

In [16]:
np.cumprod(msftAC / msftAC.shift(1))

# just for the confirmation of the above.

Date
2012-01-03          NaN
2012-01-04    1.0235344
2012-01-05    1.0339934
2012-01-06    1.0500563
2012-01-09    1.0362350
                ...
2013-12-23    1.4491997
2013-12-24    1.4674041
2013-12-26    1.4816507
2013-12-27    1.4757148
2013-12-30    1.4757148
Name: Adj Close, Length: 501, dtype: float64

In [17]:
31.9095650 / 21.6231346

# just for the confirmation above

1.4757141177856794

In [18]:
percent_change = msftAC / msftAC.shift(1) - 1
percent_change
# gives the net daily change or return.
# the price has increased by 2.3% from 2012-01-03 to 2012-01-04.

Date
2012-01-03          NaN
2012-01-04    0.0235344
2012-01-05    0.0102186
2012-01-06    0.0155348
2012-01-09   -0.0131625
                ...
2013-12-23   -0.0048914
2013-12-24    0.0125617
2013-12-26    0.0097088
2013-12-27   -0.0040063
2013-12-30    0.0000000
Name: Adj Close, Length: 501, dtype: float64

### Frequency Conversion of Time-Series Data:

In [19]:
sample = msftAC[:2]
sample
# selected first 2 rows and stored them in 'sample'

Date
2012-01-03    21.6231270
2012-01-04    22.1320133
Name: Adj Close, dtype: float64

In [27]:
sample.asfreq('H')
# to have hourly data between the two index labels.
# a new index with hourly index labels has been created by pandas, but when aligning to the original time series, only two values
# were found, thereby leaving the others filled with NaN. This default behaviour can be changed as follows:

Date
2012-01-03 00:00:00    21.6231308
2012-01-03 01:00:00           NaN
2012-01-03 02:00:00           NaN
2012-01-03 03:00:00           NaN
2012-01-03 04:00:00           NaN
2012-01-03 05:00:00           NaN
2012-01-03 06:00:00           NaN
2012-01-03 07:00:00           NaN
2012-01-03 08:00:00           NaN
2012-01-03 09:00:00           NaN
2012-01-03 10:00:00           NaN
2012-01-03 11:00:00           NaN
2012-01-03 12:00:00           NaN
2012-01-03 13:00:00           NaN
2012-01-03 14:00:00           NaN
2012-01-03 15:00:00           NaN
2012-01-03 16:00:00           NaN
2012-01-03 17:00:00           NaN
2012-01-03 18:00:00           NaN
2012-01-03 19:00:00           NaN
2012-01-03 20:00:00           NaN
2012-01-03 21:00:00           NaN
2012-01-03 22:00:00           NaN
2012-01-03 23:00:00           NaN
2012-01-04 00:00:00    22.1320095
Freq: H, Name: Adj Close, dtype: float64

In [22]:
sample.asfreq('H', method = 'ffill')
# forward fill will take the earlier known value and fill all the missing values with it.

Date
2012-01-03 00:00:00    21.6231346
2012-01-03 01:00:00    21.6231346
2012-01-03 02:00:00    21.6231346
2012-01-03 03:00:00    21.6231346
2012-01-03 04:00:00    21.6231346
2012-01-03 05:00:00    21.6231346
2012-01-03 06:00:00    21.6231346
2012-01-03 07:00:00    21.6231346
2012-01-03 08:00:00    21.6231346
2012-01-03 09:00:00    21.6231346
2012-01-03 10:00:00    21.6231346
2012-01-03 11:00:00    21.6231346
2012-01-03 12:00:00    21.6231346
2012-01-03 13:00:00    21.6231346
2012-01-03 14:00:00    21.6231346
2012-01-03 15:00:00    21.6231346
2012-01-03 16:00:00    21.6231346
2012-01-03 17:00:00    21.6231346
2012-01-03 18:00:00    21.6231346
2012-01-03 19:00:00    21.6231346
2012-01-03 20:00:00    21.6231346
2012-01-03 21:00:00    21.6231346
2012-01-03 22:00:00    21.6231346
2012-01-03 23:00:00    21.6231346
2012-01-04 00:00:00    22.1320076
Freq: H, Name: Adj Close, dtype: float64

In [23]:
sample.asfreq('H', method = 'bfill')
# backward fill will take the next known value and fill the missing values in the backward direction.

Date
2012-01-03 00:00:00    21.6231346
2012-01-03 01:00:00    22.1320076
2012-01-03 02:00:00    22.1320076
2012-01-03 03:00:00    22.1320076
2012-01-03 04:00:00    22.1320076
2012-01-03 05:00:00    22.1320076
2012-01-03 06:00:00    22.1320076
2012-01-03 07:00:00    22.1320076
2012-01-03 08:00:00    22.1320076
2012-01-03 09:00:00    22.1320076
2012-01-03 10:00:00    22.1320076
2012-01-03 11:00:00    22.1320076
2012-01-03 12:00:00    22.1320076
2012-01-03 13:00:00    22.1320076
2012-01-03 14:00:00    22.1320076
2012-01-03 15:00:00    22.1320076
2012-01-03 16:00:00    22.1320076
2012-01-03 17:00:00    22.1320076
2012-01-03 18:00:00    22.1320076
2012-01-03 19:00:00    22.1320076
2012-01-03 20:00:00    22.1320076
2012-01-03 21:00:00    22.1320076
2012-01-03 22:00:00    22.1320076
2012-01-03 23:00:00    22.1320076
2012-01-04 00:00:00    22.1320076
Freq: H, Name: Adj Close, dtype: float64

### Resampling of time-series:

In [33]:
msftAC / msftAC.shift()
# I haven't confirmed it but i think the default argument for shift is 1 which means to shift prices forward by one day.

Date
2012-01-03          NaN
2012-01-04    1.0235340
2012-01-05    1.0102190
2012-01-06    1.0155347
2012-01-09    0.9868375
                ...
2013-12-23    0.9951086
2013-12-24    1.0125612
2013-12-26    1.0097091
2013-12-27    0.9959933
2013-12-30    1.0000000
Name: Adj Close, Length: 501, dtype: float64

In [34]:
(1 + (msftAC / msftAC.shift() - 1))
# this and immediately above seems to produce the same result. Plus1 and minus1 cancels out so the result is the same as immediately above.

Date
2012-01-03          NaN
2012-01-04    1.0235340
2012-01-05    1.0102190
2012-01-06    1.0155347
2012-01-09    0.9868375
                ...
2013-12-23    0.9951086
2013-12-24    1.0125612
2013-12-26    1.0097091
2013-12-27    0.9959933
2013-12-30    1.0000000
Name: Adj Close, Length: 501, dtype: float64

In [35]:
msft_cum_ret = (1 + (msftAC / msftAC.shift() - 1)).cumprod()
msft_cum_ret
# cumprod stands for cummulative product.
# it multiplies the value on 2012-01-04 with the value on 2012-01-05 and produces the product in the index label 2012-01-05. This product 
# can be called cumulative daily return.
# $1 dollar invested on 2012-01-03 has grown to $1.475 on 2013-12-30.

Date
2012-01-03          NaN
2012-01-04    1.0235340
2012-01-05    1.0339935
2012-01-06    1.0500563
2012-01-09    1.0362350
                ...
2013-12-23    1.4492000
2013-12-24    1.4674037
2013-12-26    1.4816508
2013-12-27    1.4757143
2013-12-30    1.4757143
Name: Adj Close, Length: 501, dtype: float64

In [36]:
msft_cum_ret['1/1/2012':'1/31/2012']
# note that typing the date in this pattern is the same as typing 2012-01-04 and so on.
# this gives us daily cumulative returns for all the month as explained above.

Date
2012-01-03          NaN
2012-01-04    1.0235340
2012-01-05    1.0339935
2012-01-06    1.0500563
2012-01-09    1.0362350
2012-01-10    1.0399705
2012-01-11    1.0354876
2012-01-12    1.0459471
2012-01-13    1.0552859
2012-01-17    1.0556595
2012-01-18    1.0545387
2012-01-19    1.0504295
2012-01-20    1.1098248
2012-01-23    1.1105716
2012-01-24    1.0960034
2012-01-25    1.1042212
2012-01-26    1.1019800
2012-01-27    1.0918942
2012-01-30    1.1060890
2012-01-31    1.1031007
Name: Adj Close, dtype: float64

In [38]:
msft_cum_ret['1/1/2012':'1/31/2012'].mean()
# mean cumulative return of January 2012. It is a mean of all the daily cumulative returns in January.
# to calculate each month mean cumulative return, we have to write this command 24 times for all 24 months.

1.0686748643948816

In [39]:
msft_cum_ret['1/2012'].mean()
# an alternative to the above method to compute monthly mean.

1.0686748643948816

In [40]:
(msftAC/msftAC.shift()).mean() # mean of daily returns.

1.0008829545004747

In [41]:
msft_cum_ret

Date
2012-01-03          NaN
2012-01-04    1.0235340
2012-01-05    1.0339935
2012-01-06    1.0500563
2012-01-09    1.0362350
                ...
2013-12-23    1.4492000
2013-12-24    1.4674037
2013-12-26    1.4816508
2013-12-27    1.4757143
2013-12-30    1.4757143
Name: Adj Close, Length: 501, dtype: float64

In [42]:
msft_monthly_cum_ret = msft_cum_ret.resample("M")
msft_monthly_cum_ret
# a better and efficient alternative to the above two methods to compute monthly means.
# does not return a dataframe any longer but an object stored at some location in memory. Nevermind, all the aggregation and interpolation
# can still be validly performed as shown below.

In [43]:
def print_info(groupobject):
    for i, k in groupobject:
        print (i)
        print (k)

In [44]:
print_info(msft_monthly_cum_ret)
# the daily cumulative returns have been grouped by month. In total, we will have 24 groups since we have 24 months.

2012-01-31 00:00:00
Date
2012-01-03          NaN
2012-01-04    1.0235340
2012-01-05    1.0339935
2012-01-06    1.0500563
2012-01-09    1.0362350
2012-01-10    1.0399705
2012-01-11    1.0354876
2012-01-12    1.0459471
2012-01-13    1.0552859
2012-01-17    1.0556595
2012-01-18    1.0545387
2012-01-19    1.0504295
2012-01-20    1.1098248
2012-01-23    1.1105716
2012-01-24    1.0960034
2012-01-25    1.1042212
2012-01-26    1.1019800
2012-01-27    1.0918942
2012-01-30    1.1060890
2012-01-31    1.1031007
Name: Adj Close, dtype: float64
2012-02-29 00:00:00
Date
2012-02-01    1.1165485
2012-02-02    1.1187900
2012-02-03    1.1296229
2012-02-06    1.1281291
2012-02-07    1.1337318
2012-02-08    1.1453121
2012-02-09    1.1494214
2012-02-10    1.1393354
2012-02-13    1.1423237
2012-02-14    1.1374357
2012-02-15    1.1299155
2012-02-16    1.1765408
2012-02-17    1.1750367
2012-02-21    1.1821809
2012-02-22    1.1757887
2012-02-23    1.1795488
2012-02-24    1.1836845
2012-02-27    1.1787968
2012-02-28    1.1983497
2012-02-29    1.1934613
Name: Adj Close, dtype: float64
2012-03-31 00:00:00
Date
2012-03-01    1.2141418
2012-03-02    1.2062459
2012-03-05    1.1957175
2012-03-06    1.1866931
2012-03-07    1.1972216
2012-03-08    1.2036135
2012-03-09    1.2028615
2012-03-12    1.2047418
2012-03-13    1.2284305
2012-03-14    1.2321905
2012-03-15    1.2351984
2012-03-16    1.2257982
2012-03-19    1.2107579
2012-03-20    1.2028615
2012-03-21    1.1998537
2012-03-22    1.2032375
2012-03-23    1.2036135
2012-03-26    1.2254223
2012-03-27    1.2227905
2012-03-28    1.2103818
2012-03-29    1.2077496
2012-03-30    1.2130136
Name: Adj Close, dtype: float64
2012-04-30 00:00:00
Date
2012-04-02    1.2141418
2012-04-03    1.2009814
2012-04-04    1.1735327
2012-04-05    1.1851894
2012-04-09    1.1693966
2012-04-10    1.1457078
2012-04-11    1.1411955
2012-04-12    1.1648844
2012-04-13    1.1584919
2012-04-16    1.1686442
2012-04-17    1.1821809
2012-04-18    1.1709007
2012-04-19    1.1660123
2012-04-20    1.2190300
2012-04-23    1.2077496
2012-04-24    1.2002293
2012-04-25    1.2107579
2012-04-26    1.2073738
2012-04-27    1.2024857
2012-04-30    1.2039898
Name: Adj Close, dtype: float64
2012-05-31 00:00:00
Date
2012-05-01    1.2036135
2012-05-02    1.1957175
2012-05-03    1.1942133
2012-05-04    1.1648844
2012-05-07    1.1524762
2012-05-08    1.1468358
2012-05-09    1.1566120
2012-05-10    1.1558600
2012-05-11    1.1716528
2012-05-14    1.1536040
2012-05-15    1.1433850
2012-05-16    1.1316521
2012-05-17    1.1248396
2012-05-18    1.1078083
2012-05-21    1.1259754
2012-05-22    1.1263537
2012-05-23    1.1017525
2012-05-24    1.1002386
2012-05-25    1.0998601
2012-05-29    1.1187840
2012-05-30    1.1104575
2012-05-31    1.1047803
Name: Adj Close, dtype: float64
2012-06-30 00:00:00
Date
2012-06-01    1.0767728
2012-06-04    1.0805578
2012-06-05    1.0790435
2012-06-06    1.1108360
2012-06-07    1.1062942
2012-06-08    1.1221902
2012-06-11    1.0938047
2012-06-12    1.1085653
2012-06-13    1.1025095
2012-06-14    1.1104575
2012-06-15    1.1361938
2012-06-18    1.1293815
2012-06-19    1.1619307
2012-06-20    1.1706357
2012-06-21    1.1407357
2012-06-22    1.1619307
2012-06-25    1.1305168
2012-06-26    1.1361938
2012-06-27    1.1418715
2012-06-28    1.1320308
2012-06-29    1.1577676
Name: Adj Close, dtype: float64
2012-07-31 00:00:00
Date
2012-07-02    1.1566317
2012-07-03    1.1642013
2012-07-05    1.1619307
2012-07-06    1.1426280
2012-07-09    1.1354370
2012-07-10    1.1255967
2012-07-11    1.1089437
2012-07-12    1.0835853
2012-07-13    1.1123497
2012-07-16    1.1142424
2012-07-17    1.1225688
2012-07-18    1.1524687
2012-07-19    1.1607953
2012-07-20    1.1399787
2012-07-23    1.1081866
2012-07-24    1.1032661
2012-07-25    1.0911549
2012-07-26    1.1036450
2012-07-27    1.1263537
2012-07-30    1.1218117
2012-07-31    1.1153775
Name: Adj Close, dtype: float64
2012-08-31 00:00:00
Date
2012-08-01    1.1131068
2012-08-02    1.1047803
2012-08-03    1.1259754
2012-08-06    1.1335449
2012-08-07    1.1452776
2012-08-08    1.1479268
2012-08-09    1.1543609
2012-08-10    1.1513335
2012-08-13    1.1501977
2012-08-14    1.1479119
2012-08-15    1.1505785
2012-08-16    1.1726761
2012-08-17    1.1772477
2012-08-20    1.1711520
2012-08-21    1.1734376
2012-08-22    1.1635324
2012-08-23    1.1528647
2012-08-24    1.1642940
2012-08-27    1.1692470
2012-08-28    1.1669611
2012-08-29    1.1677232
2012-08-30    1.1551506
2012-08-31    1.1741998
Name: Adj Close, dtype: float64
2012-09-30 00:00:00
Date
2012-09-04    1.1578175
2012-09-05    1.1578175
2012-09-06    1.1943920
2012-09-07    1.1791529
2012-09-10    1.1703900
2012-09-11    1.1730569
2012-09-12    1.1726761
2012-09-13    1.1787718
2012-09-14    1.1890584
2012-09-17    1.1890584
2012-09-18    1.1879154
2012-09-19    1.1829626
2012-09-20    1.1982021
2012-09-21    1.1882963
2012-09-24    1.1726761
2012-09-25    1.1578175
2012-09-26    1.1494361
2012-09-27    1.1490550
2012-09-28    1.1338154
Name: Adj Close, dtype: float64
2012-10-31 00:00:00
Date
2012-10-01    1.1235286
2012-10-02    1.1300054
2012-10-03    1.1376254
2012-10-04    1.1441019
2012-10-05    1.1372443
2012-10-08    1.1345773
2012-10-09    1.1155280
2012-10-10    1.1040985
2012-10-11    1.1029554
2012-10-12    1.1124800
2012-10-15    1.1242906
2012-10-16    1.1235286
2012-10-17    1.1273385
2012-10-18    1.1239096
2012-10-19    1.0911448
2012-10-22    1.0667619
2012-10-23    1.0686667
2012-10-24    1.0629519
2012-10-25    1.0621899
2012-10-26    1.0747625
2012-10-31    1.0873352
Name: Adj Close, dtype: float64
2012-11-30 00:00:00
Date
2012-11-01    1.1246718
2012-11-02    1.1239096
2012-11-05    1.1288624
2012-11-06    1.1376254
2012-11-07    1.1079078
2012-11-08    1.0976215
2012-11-09    1.0983836
2012-11-12    1.0751432
2012-11-13    1.0405729
2012-11-14    1.0309698
2012-11-15    1.0240561
2012-11-16    1.0186783
2012-11-19    1.0267448
2012-11-20    1.0259762
2012-11-21    1.0351949
2012-11-23    1.0640040
2012-11-26    1.0520962
2012-11-27    1.0401889
2012-11-28    1.0509442
2012-11-29    1.0351949
2012-11-30    1.0225195
Name: Adj Close, dtype: float64
2012-12-31 00:00:00
Date
2012-12-03    1.0152212
2012-12-04    1.0129166
2012-12-05    1.0244398
2012-12-06    1.0267448
2012-12-07    1.0163731
2012-12-10    1.0348111
2012-12-11    1.0494076
2012-12-12    1.0463347
2012-12-13    1.0413410
2012-12-14    1.0298176
2012-12-17    1.0409569
2012-12-18    1.0586265
2012-12-19    1.0490233
2012-12-20    1.0632358
2012-12-21    1.0544012
2012-12-24    1.0394204
2012-12-26    1.0317382
2012-12-27    1.0355797
2012-12-28    1.0198306
2012-12-31    1.0259762
Name: Adj Close, dtype: float64
2013-01-31 00:00:00
Date
2013-01-02    1.0609313
2013-01-03    1.0467188
2013-01-04    1.0271285
2013-01-07    1.0252082
2013-01-08    1.0198306
2013-01-09    1.0255925
2013-01-10    1.0163731
2013-01-11    1.0305859
2013-01-14    1.0328907
2013-01-15    1.0451822
2013-01-16    1.0386524
2013-01-17    1.0467188
2013-01-18    1.0467188
2013-01-22    1.0428775
2013-01-23    1.0605471
2013-01-24    1.0613151
2013-01-25    1.0709180
2013-01-28    1.0720706
2013-01-29    1.0759120
2013-01-30    1.0697659
2013-01-31    1.0544012
Name: Adj Close, dtype: float64
2013-02-28 00:00:00
Date
2013-02-01    1.0728388
2013-02-04    1.0540172
2013-02-05    1.0563220
2013-02-06    1.0501758
2013-02-07    1.0478712
2013-02-08    1.0582424
2013-02-11    1.0701500
2013-02-12    1.0709180
2013-02-13    1.0766798
2013-02-14    1.0770643
2013-02-15    1.0759120
2013-02-19    1.0863687
2013-02-20    1.0793973
2013-02-21    1.0646801
2013-02-22    1.0751372
2013-02-25    1.0600326
2013-02-26    1.0600326
2013-02-27    1.0770735
2013-02-28    1.0766863
Name: Adj Close, dtype: float64
2013-03-31 00:00:00
Date
2013-03-01    1.0824956
2013-03-04    1.0902417
2013-03-05    1.0979876
2013-03-06    1.0879178
2013-03-07    1.0898548
2013-03-08    1.0844322
2013-03-11    1.0793973
2013-03-12    1.0809467
2013-03-13    1.0813341
2013-03-14    1.0898548
2013-03-15    1.0859816
2013-03-18    1.0883050
2013-03-19    1.0914038
2013-03-20    1.0968258
2013-03-21    1.0886926
2013-03-22    1.0941149
2013-03-25    1.0906289
2013-03-26    1.0906289
2013-03-27    1.0987622
2013-03-28    1.1080574
Name: Adj Close, dtype: float64
2013-04-30 00:00:00
Date
2013-04-01    1.1080574
2013-04-02    1.1154160
2013-04-03    1.1061208
2013-04-04    1.1076699
2013-04-05    1.1115430
2013-04-08    1.1072825
2013-04-09    1.1467874
2013-04-10    1.1727363
2013-04-11    1.1208382
2013-04-12    1.1150289
2013-04-15    1.1111558
2013-04-16    1.1220000
2013-04-17    1.1165778
2013-04-18    1.1150289
2013-04-19    1.1529838
2013-04-22    1.1940370
2013-04-23    1.1851294
2013-04-24    1.2300558
2013-04-25    1.2370273
2013-04-26    1.2312177
2013-04-29    1.2629764
2013-04-30    1.2819536
Name: Adj Close, dtype: float64
2013-05-31 00:00:00
Date
2013-05-01    1.2672365
2013-05-02    1.2842774
2013-05-03    1.2970583
2013-05-06    1.3071280
2013-05-07    1.2900872
2013-05-08    1.2776936
2013-05-09    1.2649128
2013-05-10    1.2660746
2013-05-13    1.2792428
2013-05-14    1.3077136
2013-05-15    1.3201938
2013-05-16    1.3291640
2013-05-17    1.3599752
2013-05-20    1.3681659
2013-05-21    1.3591953
2013-05-22    1.3498351
2013-05-23    1.3318946
2013-05-24    1.3365749
2013-05-28    1.3658253
2013-05-29    1.3603657
2013-05-30    1.3662157
2013-05-31    1.3611450
Name: Adj Close, dtype: float64
2013-06-30 00:00:00
Date
2013-06-03    1.3880565
2013-06-04    1.3646560
2013-06-05    1.3564655
2013-06-06    1.3634853
2013-06-07    1.3911760
2013-06-10    1.3833760
2013-06-11    1.3588055
2013-06-12    1.3650454
2013-06-13    1.3541255
2013-06-14    1.3416449
2013-06-17    1.3650454
2013-06-18    1.3642656
2013-06-19    1.3490550
2013-06-20    1.3061535
2013-06-21    1.2975733
2013-06-24    1.3151238
2013-06-25    1.3131738
2013-06-26    1.3396944
2013-06-27    1.3502250
2013-06-28    1.3471047
Name: Adj Close, dtype: float64
2013-07-31 00:00:00
Date
2013-07-01    1.3400845
2013-07-02    1.3237039
2013-07-03    1.3264345
2013-07-05    1.3342349
2013-07-08    1.3389148
2013-07-09    1.3396944
2013-07-10    1.3533450
2013-07-11    1.3919563
2013-07-12    1.3911760
2013-07-15    1.4106774
2013-07-16    1.4145770
2013-07-17    1.3939069
2013-07-18    1.3822065
2013-07-19    1.2246411
2013-07-22    1.2484316
2013-07-23    1.2410215
2013-07-24    1.2464816
2013-07-25    1.2242506
2013-07-26    1.2332213
2013-07-29    1.2301011
2013-07-30    1.2421915
2013-07-31    1.2418018
Name: Adj Close, dtype: float64
2013-08-31 00:00:00
Date
2013-08-01    1.2351712
2013-08-02    1.2437515
2013-08-05    1.2363412
2013-08-06    1.2316610
2013-08-07    1.2503819
2013-08-08    1.2827529
2013-08-09    1.2753427
2013-08-12    1.2819728
2013-08-13    1.2658695
2013-08-14    1.2705829
2013-08-15    1.2485881
2013-08-16    1.2489812
2013-08-19    1.2328775
2013-08-20    1.2419113
2013-08-21    1.2415183
2013-08-22    1.2721536
2013-08-23    1.3648455
2013-08-26    1.3412800
2013-08-27    1.3063239
2013-08-28    1.2968978
2013-08-29    1.3177140
2013-08-30    1.3118228
Name: Adj Close, dtype: float64
2013-09-30 00:00:00
Date
2013-09-03    1.2521232
2013-09-04    1.2254153
2013-09-05    1.2265936
2013-09-06    1.2234516
2013-09-09    1.2434824
2013-09-10    1.2721536
2013-09-11    1.2859005
2013-09-12    1.2839368
2013-09-13    1.2972905
2013-09-16    1.2882572
2013-09-17    1.2933631
2013-09-18    1.3086808
2013-09-19    1.3212487
2013-09-20    1.2878644
2013-09-23    1.2859005
2013-09-24    1.2745104
2013-09-25    1.2768667
2013-09-26    1.2870787
2013-09-27    1.3067166
2013-09-30    1.3071098
Name: Adj Close, dtype: float64
2013-10-31 00:00:00
Date
2013-10-01    1.3188927
2013-10-02    1.3322461
2013-10-03    1.3298898
2013-10-04    1.3306753
2013-10-07    1.3078951
2013-10-08    1.2965049
2013-10-09    1.2988618
2013-10-10    1.3259622
2013-10-11    1.3404945
2013-10-14    1.3530627
2013-10-15    1.3546334
2013-10-16    1.3605249
2013-10-17    1.3715223
2013-10-18    1.3730931
2013-10-21    1.3742721
2013-10-22    1.3581689
2013-10-23    1.3259622
2013-10-24    1.3243909
2013-10-25    1.4033359
2013-10-28    1.3970519
2013-10-29    1.3950886
2013-10-30    1.3958738
2013-10-31    1.3907677
Name: Adj Close, dtype: float64
2013-11-30 00:00:00
Date
2013-11-01    1.3954807
2013-11-04    1.4115842
2013-11-05    1.4390778
2013-11-06    1.4995630
2013-11-07    1.4728550
2013-11-08    1.4838522
2013-11-11    1.4763893
2013-11-12    1.4673570
2013-11-13    1.4987773
2013-11-14    1.4932785
2013-11-15    1.4862086
2013-11-18    1.4610720
2013-11-19    1.4539486
2013-11-20    1.4674037
2013-11-21    1.4800673
2013-11-22    1.4867952
2013-11-25    1.4895654
2013-11-26    1.4780886
2013-11-27    1.4879819
2013-11-29    1.5089567
Name: Adj Close, dtype: float64
2013-12-31 00:00:00
Date
2013-12-02    1.5216205
2013-12-03    1.5160797
2013-12-04    1.5410112
2013-12-05    1.5038119
2013-12-06    1.5180579
2013-12-09    1.5319090
2013-12-10    1.5081651
2013-12-11    1.4883780
2013-12-12    1.4729437
2013-12-13    1.4519707
2013-12-16    1.4598847
2013-12-17    1.4452424
2013-12-18    1.4476168
2013-12-19    1.4345574
2013-12-20    1.4563235
2013-12-23    1.4492000
2013-12-24    1.4674037
2013-12-26    1.4816508
2013-12-27    1.4757143
2013-12-30    1.4757143
Name: Adj Close, dtype: float64

In [45]:
len(msft_monthly_cum_ret)
# 24 groups confirmed.

24

In [47]:
msft_monthly_cum_ret.size()
# size of each group.

Date
2012-01-31    20
2012-02-29    20
2012-03-31    22
2012-04-30    20
2012-05-31    22
2012-06-30    21
2012-07-31    21
2012-08-31    23
2012-09-30    19
2012-10-31    21
2012-11-30    21
2012-12-31    20
2013-01-31    21
2013-02-28    19
2013-03-31    20
2013-04-30    22
2013-05-31    22
2013-06-30    20
2013-07-31    22
2013-08-31    22
2013-09-30    20
2013-10-31    23
2013-11-30    20
2013-12-31    20
Freq: M, Name: Adj Close, dtype: int64

In [48]:
msft_monthly_cum_ret.mean()

Date
2012-01-31    1.0686749
2012-02-29    1.1556977
2012-03-31    1.2105698
2012-04-30    1.1846438
2012-05-31    1.1405162
2012-06-30    1.1233438
2012-07-31    1.1262454
2012-08-31    1.1536296
2012-09-30    1.1727562
2012-10-31    1.1073821
2012-11-30    1.0648222
2012-12-31    1.0358098
2013-01-31    1.0462066
2013-02-28    1.0678737
2013-03-31    1.0898932
2013-04-30    1.1568920
2013-05-31    1.3204534
2013-06-30    1.3507126
2013-07-31    1.3124116
2013-08-31    1.2726701
2013-09-30    1.2773972
2013-10-31    1.3503987
2013-11-30    1.4719151
2013-12-31    1.4823628
Freq: M, Name: Adj Close, dtype: float64

In [49]:
msft_cum_ret['2/2012'].mean()
# to compare and confirm the mean of feb in immediately above series. Confirmed and the same.

1.155697714194582

In [50]:
## The above work is almost the end of page 94 in the book. After that, for about 3 pages, the discussion in the book cannot be
# implemented here since there is change in the newer version of pandas. But what we can do something extra and interesting follows
# as:

In [51]:
msft

,High,Low,Open,Close,Volume,Adj Close
Date,,,,,,
2012-01-03,26.9599991,26.3899994,26.5499992,26.7700005,64731500.0,21.6231308
2012-01-04,27.4699993,26.7800007,26.8199997,27.3999996,80516100.0,22.1320095
2012-01-05,27.7299995,27.2900009,27.3799992,27.6800003,56081400.0,22.3581772
2012-01-06,28.1900005,27.5300007,27.5300007,28.1100006,99455500.0,22.7055054
2012-01-09,28.1000004,27.7199993,28.0499992,27.7399998,59706800.0,22.4066448
...,...,...,...,...,...,...
2013-12-23,36.8899994,36.5499992,36.8100014,36.6199989,25128700.0,31.3362408
2013-12-24,37.1699982,36.6399994,36.7200012,37.0800018,14243000.0,31.7298622
2013-12-26,37.4900017,37.1699982,37.2000008,37.4399986,17612800.0,32.0379295
2013-12-27,37.6199989,37.1699982,37.5800018,37.2900009,14563000.0,31.9095631
2013-12-30,37.3800011,36.9000015,37.2200012,37.2900009,16290500.0,31.9095631

In [52]:
msft_resample = msft.resample('M')
# the frequency has been changed to Monthly from Daily.

In [53]:
msft_resample

In [54]:
for i, k in msft_resample:
    print(i)
    print(k)
# the data has been grouped on monthly basis into 24 groups since we have 24 months.

2012-01-31 00:00:00
                  High         Low        Open       Close       Volume  \
Date
2012-01-03  26.9599991  26.3899994  26.5499992  26.7700005   64731500.0
2012-01-04  27.4699993  26.7800007  26.8199997  27.3999996   80516100.0
2012-01-05  27.7299995  27.2900009  27.3799992  27.6800003   56081400.0
2012-01-06  28.1900005  27.5300007  27.5300007  28.1100006   99455500.0
2012-01-09  28.1000004  27.7199993  28.0499992  27.7399998   59706800.0
2012-01-10  28.1499996  27.7500000  27.9300003  27.8400002   60014400.0
2012-01-11  27.9799995  27.3700008  27.4300003  27.7199993   65582400.0
2012-01-12  28.0200005  27.6499996  27.8700008  28.0000000   49370800.0
2012-01-13  28.2500000  27.7900009  27.9300003  28.2500000   60196100.0
2012-01-17  28.6499996  28.1700001  28.3999996  28.2600002   72395300.0
2012-01-18  28.3999996  27.9699993  28.3099995  28.2299995   64860600.0
2012-01-19  28.4400005  28.0300007  28.1599998  28.1200008   74053500.0
2012-01-20  29.7399998  28.7500000  28.8199997  29.7099991  165902900.0
2012-01-23  29.9500008  29.3500004  29.5499992  29.7299995   76078100.0
2012-01-24  29.5699997  29.1800003  29.4699993  29.3400002   51703300.0
2012-01-25  29.6499996  29.0699997  29.0699997  29.5599995   59231700.0
2012-01-26  29.7000008  29.3999996  29.6100006  29.5000000   49102800.0
2012-01-27  29.5300007  29.1700001  29.4500008  29.2299995   44187700.0
2012-01-30  29.6200008  28.8299999  28.9699993  29.6100006   51114800.0
2012-01-31  29.7000008  29.2299995  29.6599998  29.5300007   50572400.0

             Adj Close
Date
2012-01-03  21.6231308
2012-01-04  22.1320095
2012-01-05  22.3581772
2012-01-06  22.7055054
2012-01-09  22.4066448
2012-01-10  22.4874172
2012-01-11  22.3904839
2012-01-12  22.6166515
2012-01-13  22.8185844
2012-01-17  22.8266640
2012-01-18  22.8024273
2012-01-19  22.7135754
2012-01-20  23.9978867
2012-01-23  24.0140343
2012-01-24  23.6990242
2012-01-25  23.8767185
2012-01-26  23.8282585
2012-01-27  23.6101704
2012-01-30  23.9171066
2012-01-31  23.8524914
2012-02-29 00:00:00
                  High         Low        Open       Close      Volume  \
Date
2012-02-01  30.0499992  29.7600002  29.7900009  29.8899994  67409900.0
2012-02-02  30.1700001  29.7099991  29.8999996  29.9500008  52223300.0
2012-02-03  30.3999996  30.0900002  30.1399994  30.2399998  41838500.0
2012-02-06  30.2199993  29.9699993  30.0400009  30.2000008  28039700.0
2012-02-07  30.4899998  30.0499992  30.1499996  30.3500004  39242400.0
2012-02-08  30.6700001  30.2199993  30.2600002  30.6599998  49659100.0
2012-02-09  30.7999992  30.4799995  30.6800003  30.7700005  50481600.0
2012-02-10  30.7999992  30.3600006  30.6399994  30.5000000  44605300.0
2012-02-13  30.7700005  30.4300003  30.6299992  30.5799999  33319800.0
2012-02-14  30.4599991  29.8500004  30.3299999  30.2500000  59644000.0
2012-02-15  30.3899994  30.0300007  30.3299999  30.0499992  43311300.0
2012-02-16  31.5499992  30.2999992  30.3099995  31.2900009  94705100.0
2012-02-17  31.3199997  30.9500008  31.2000008  31.2500000  70036500.0
2012-02-21  31.6100006  31.1499996  31.1800003  31.4400005  50829900.0
2012-02-22  31.6800003  31.1800003  31.4500008  31.2700005  49253200.0
2012-02-23  31.5900002  31.0000000  31.2000008  31.3700008  35034700.0
2012-02-24  31.5000000  31.2399998  31.4799995  31.4799995  35575400.0
2012-02-27  31.5000000  31.1000004  31.2399998  31.3500004  34568400.0
2012-02-28  31.9300003  31.3799992  31.4099998  31.8700008  45230600.0
2012-02-29  32.0000000  31.6100006  31.8899994  31.7399998  59323600.0

             Adj Close
Date
2012-02-01  24.1432743
2012-02-02  24.1917419
2012-02-03  24.4259834
2012-02-06  24.3936825
2012-02-07  24.5148315
2012-02-08  24.7652340
2012-02-09  24.8540897
2012-02-10  24.6359978
2012-02-13  24.7006149
2012-02-14  24.5949211
2012-02-15  24.4323101
2012-02-16  25.4404964
2012-02-17  25.4079723
2012-02-21  25.5624523
2012-02-22  25.4242325
2012-02-23  25.5055389
2012-02-24  25.5949650
2012-02-27  25.4892769
2012-02-28  25.9120712
2012-02-29  25.8063698
2012-03-31 00:00:00
                  High         Low        Open       Close      Volume  \
Date
2012-03-01  32.3899994  31.8500004  31.9300003  32.2900009  77344100.0
2012-03-02  32.4399986  32.0000000  32.3100014  32.0800018  47314200.0
2012-03-05  32.0499992  31.6200008  32.0099983  31.7999992  45240000.0
2012-03-06  31.9799995  31.4899998  31.5400009  31.5599995  51932900.0
2012-03-07  31.9200001  31.5300007  31.6700001  31.8400002  34340400.0
2012-03-08  32.2099991  31.8999996  32.0400009  32.0099983  36747400.0
2012-03-09  32.1599998  31.9200001  32.0999985  31.9899998  34628400.0
2012-03-12  32.2000008  31.8199997  31.9699993  32.0400009  34073600.0
2012-03-13  32.6899986  32.1500015  32.2400017  32.6699982  48951700.0
2012-03-14  32.8800011  32.4900017  32.5299988  32.7700005  41986900.0
2012-03-15  32.9399986  32.5800018  32.7900009  32.8499985  49068300.0
2012-03-16  32.9500008  32.5000000  32.9099998  32.5999985  65626400.0
2012-03-19  32.6100006  32.1500015  32.5400009  32.2000008  44789200.0
2012-03-20  32.1500015  31.7399998  32.0999985  31.9899998  41566800.0
2012-03-21  32.1500015  31.8199997  31.9599991  31.9099998  37928600.0
2012-03-22  32.0900002  31.7900009  31.8099995  32.0000000  31749500.0
2012-03-23  32.1100006  31.7199993  32.0999985  32.0099983  35912200.0
2012-03-26  32.6100006  32.1500015  32.1899986  32.5900002  36758300.0
2012-03-27  32.7000008  32.4000015  32.6500015  32.5200005  36274900.0
2012-03-28  32.7000008  32.0400009  32.5200005  32.1899986  41344800.0
2012-03-29  32.1899986  31.8099995  32.0600014  32.1199989  37038500.0
2012-03-30  32.4099998  32.0400009  32.4000015  32.2599983  31749400.0

             Adj Close
Date
2012-03-01  26.2535477
2012-03-02  26.0828133
2012-03-05  25.8551559
2012-03-06  25.6600208
2012-03-07  25.8876801
2012-03-08  26.0258923
2012-03-09  26.0096321
2012-03-12  26.0502892
2012-03-13  26.5625134
2012-03-14  26.6438160
2012-03-15  26.7088566
2012-03-16  26.5055943
2012-03-19  26.1803761
2012-03-20  26.0096321
2012-03-21  25.9445934
2012-03-22  26.0177612
2012-03-23  26.0258923
2012-03-26  26.4974670
2012-03-27  26.4405594
2012-03-28  26.1722431
2012-03-29  26.1153278
2012-03-30  26.2291527
2012-04-30 00:00:00
                  High         Low        Open       Close       Volume  \
Date
2012-04-02  32.4599991  31.9500008  32.2200012  32.2900009   35853600.0
2012-04-03  32.1899986  31.6599998  32.1599998  31.9400005   42752100.0
2012-04-04  31.6900005  31.0499992  31.6599998  31.2099991   49455900.0
2012-04-05  31.6299992  31.0499992  31.1499996  31.5200005   50368600.0
2012-04-09  31.3999996  30.9699993  31.2199993  31.1000004   31056400.0
2012-04-10  31.1900005  30.2999992  31.0599995  30.4699993   54131300.0
2012-04-11  30.5300007  30.2299995  30.4300003  30.3500004   43014000.0
2012-04-12  31.0400009  30.4200001  30.4799995  30.9799995   38304000.0
2012-04-13  31.1599998  30.7199993  30.8899994  30.8099995   39749200.0
2012-04-16  31.1900005  30.7700005  30.9899998  31.0799999   38124800.0
2012-04-17  31.6100006  31.2000008  31.2700005  31.4400005   34361500.0
2012-04-18  31.3099995  31.0400009  31.2800007  31.1399994   40552900.0
2012-04-19  31.6800003  30.9400005  31.1299992  31.0100002   54781200.0
2012-04-20  32.8899994  32.0499992  32.1500015  32.4199982  106045000.0
2012-04-23  32.5000000  32.0299988  32.3100014  32.1199989   61398200.0
2012-04-24  32.5200005  31.8299999  32.2099991  31.9200001   40871100.0
2012-04-25  32.3199997  31.8700008  31.9200001  32.2000008   62495500.0
2012-04-26  32.2299995  31.9200001  32.1199989  32.1100006   40308100.0
2012-04-27  32.2200012  31.8799992  32.1199989  31.9799995   41419100.0
2012-04-30  32.1100006  31.9200001  31.9799995  32.0200005   35697200.0

             Adj Close
Date
2012-04-02  26.2535477
2012-04-03  25.9689770
2012-04-04  25.3754520
2012-04-05  25.6275063
2012-04-09  25.2860146
2012-04-10  24.7737904
2012-04-11  24.6762199
2012-04-12  25.1884480
2012-04-13  25.0502224
2012-04-16  25.2697468
2012-04-17  25.5624523
2012-04-18  25.3185387
2012-04-19  25.2128372
2012-04-20  26.3592453
2012-04-23  26.1153278
2012-04-24  25.9527149
2012-04-25  26.1803761
2012-04-26  26.1072006
2012-04-27  26.0015049
2012-04-30  26.0340290
2012-05-31 00:00:00
                  High         Low        Open       Close      Volume  \
Date
2012-05-01  32.3400002  31.9500008  32.0499992  32.0099983  43832300.0
2012-05-02  31.9300003  31.6399994  31.8500004  31.7999992  37385300.0
2012-05-03  31.8999996  31.6100006  31.8799992  31.7600002  31501300.0
2012-05-04  31.5699997  30.9200001  31.4500008  30.9799995  57927200.0
2012-05-07  30.8600006  30.5699997  30.7000008  30.6499996  48641400.0
2012-05-08  30.7800007  30.1700001  30.4799995  30.5000000  46328300.0
2012-05-09  30.8299999  30.1000004  30.1900005  30.7600002  50309300.0
2012-05-10  31.0200005  30.4500008  30.8600006  30.7399998  43839200.0
2012-05-11  31.5400009  30.6900005  30.6900005  31.1599998  43459300.0
2012-05-14  31.0400009  30.6399994  30.8199997  30.6800003  40528900.0
2012-05-15  30.7999992  30.1499996  30.6399994  30.2099991  61822800.0
2012-05-16  30.3199997  29.7399998  30.3099995  29.8999996  60083700.0
2012-05-17  30.2099991  29.7099991  29.9899998  29.7199993  48484000.0
2012-05-18  29.8099995  29.1700001  29.7900009  29.2700005  56205300.0
2012-05-21  29.7900009  29.0599995  29.1000004  29.7500000  38787900.0
2012-05-22  29.8799992  29.5000000  29.6900005  29.7600002  39504900.0
2012-05-23  29.3999996  28.6399994  29.3500004  29.1100006  65171000.0
2012-05-24  29.2999992  28.7600002  29.1599998  29.0699997  52575000.0
2012-05-25  29.3600006  29.0100002  29.2000008  29.0599995  29507200.0
2012-05-29  29.7199993  29.2199993  29.3799992  29.5599995  37758800.0
2012-05-30  29.4799995  29.1200008  29.3500004  29.3400002  41585500.0
2012-05-31  29.4200001  28.9400005  29.2999992  29.1900005  39134000.0

             Adj Close
Date
2012-05-01  26.0258923
2012-05-02  25.8551559
2012-05-03  25.8226299
2012-05-04  25.1884480
2012-05-07  24.9201431
2012-05-08  24.7981796
2012-05-09  25.0095730
2012-05-10  24.9933128
2012-05-11  25.3348026
2012-05-14  24.9445305
2012-05-15  24.7235641
2012-05-16  24.4698620
2012-05-17  24.3225536
2012-05-18  23.9542847
2012-05-21  24.3471127
2012-05-22  24.3552933
2012-05-23  23.8233376
2012-05-24  23.7906036
2012-05-25  23.7824192
2012-05-29  24.1916122
2012-05-30  24.0115681
2012-05-31  23.8888092
2012-06-30 00:00:00
                  High         Low        Open       Close      Volume  \
Date
2012-06-01  28.9599991  28.4400005  28.7600002  28.4500008  56634300.0
2012-06-04  28.7800007  28.3199997  28.6200008  28.5499992  47926300.0
2012-06-05  28.7500000  28.3899994  28.5100002  28.5100002  45715400.0
2012-06-06  29.3700008  28.8099995  28.8799992  29.3500004  46860500.0
2012-06-07  29.7000008  29.1700001  29.6399994  29.2299995  37792800.0
2012-06-08  29.6800003  29.0499992  29.2099991  29.6499996  42551100.0
2012-06-11  29.8099995  28.8199997  29.7299995  28.8999996  46361900.0
2012-06-12  29.2999992  28.8400002  29.1000004  29.2900009  35337900.0
2012-06-13  29.4400005  29.0499992  29.2199993  29.1299992  32984600.0
2012-06-14  29.4599991  28.8799992  29.3299999  29.3400002  39458900.0
2012-06-15  30.0799999  29.4899998  29.5900002  30.0200005  62314400.0
2012-06-18  30.0300007  29.7099991  29.9899998  29.8400002  58679900.0
2012-06-19  31.1100006  30.0499992  30.1900005  30.7000008  75725800.0
2012-06-20  31.0499992  30.6399994  30.9300003  30.9300003  36257100.0
2012-06-21  31.1399994  30.0599995  30.9599991  30.1399994  48456600.0
2012-06-22  30.7299995  30.0300007  30.2999992  30.7000008  45098100.0
2012-06-25  30.3199997  29.6200008  30.2999992  29.8700008  42217200.0
2012-06-26  30.2700005  29.9400005  30.0000000  30.0200005  38421300.0
2012-06-27  30.5000000  30.0300007  30.1900005  30.1700001  33781700.0
2012-06-28  30.0499992  29.4200001  29.9799995  29.9099998  45328400.0
2012-06-29  30.6900005  30.1399994  30.4500008  30.5900002  55227200.0

             Adj Close
Date
2012-06-01  23.2831993
2012-06-04  23.3650417
2012-06-05  23.3322983
2012-06-06  24.0197525
2012-06-07  23.9215431
2012-06-08  24.2652664
2012-06-11  23.6514816
2012-06-12  23.9706535
2012-06-13  23.8397064
2012-06-14  24.0115681
2012-06-15  24.5680676
2012-06-18  24.4207630
2012-06-19  25.1245785
2012-06-20  25.3128090
2012-06-21  24.6662769
2012-06-22  25.1245785
2012-06-25  24.4453125
2012-06-26  24.5680676
2012-06-27  24.6908360
2012-06-28  24.4780502
2012-06-29  25.0345592
2012-07-31 00:00:00
                  High         Low        Open       Close      Volume  \
Date
2012-07-02  30.6200008  30.2099991  30.6200008  30.5599995  30589100.0
2012-07-03  30.7600002  30.1700001  30.2299995  30.7600002  20938100.0
2012-07-05  30.7800007  30.3799992  30.5900002  30.7000008  28801900.0
2012-07-06  30.7000008  29.9500008  30.6100006  30.1900005  38294800.0
2012-07-09  30.2299995  29.7800007  30.1200008  30.0000000  30680800.0
2012-07-10  30.2199993  29.5100002  30.0799999  29.7399998  37534100.0
2012-07-11  29.7399998  29.1100006  29.7099991  29.2999992  39184900.0
2012-07-12  29.1800003  28.5400009  29.1499996  28.6299992  63523600.0
2012-07-13  29.4799995  28.7199993  28.7600002  29.3899994  39085000.0
2012-07-16  29.5300007  29.0400009  29.4799995  29.4400005  27900600.0
2012-07-17  29.8600006  29.2000008  29.6399994  29.6599998  33771300.0
2012-07-18  30.4500008  29.4599991  29.6000004  30.4500008  41090400.0
2012-07-19  30.7999992  30.3799992  30.5100002  30.6700001  46663200.0
2012-07-20  31.0499992  30.0499992  31.0000000  30.1200008  64021700.0
2012-07-23  29.5799999  29.0100002  29.5699997  29.2800007  55151900.0
2012-07-24  29.3600006  28.8999996  29.2399998  29.1499996  47723300.0
2012-07-25  29.3299999  28.7800007  29.2399998  28.8299999  45579500.0
2012-07-26  29.5000000  29.0900002  29.2299995  29.1599998  45301400.0
2012-07-27  29.8500004  29.1800003  29.4799995  29.7600002  44242600.0
2012-07-30  29.8199997  29.4599991  29.7500000  29.6399994  28905000.0
2012-07-31  29.7099991  29.3299999  29.4799995  29.4699993  37620900.0

             Adj Close
Date
2012-07-02  25.0099983
2012-07-03  25.1736774
2012-07-05  25.1245785
2012-07-06  24.7071953
2012-07-09  24.5517025
2012-07-10  24.3389244
2012-07-11  23.9788342
2012-07-12  23.4305058
2012-07-13  24.0524826
2012-07-16  24.0934086
2012-07-17  24.2734528
2012-07-18  24.9199810
2012-07-19  25.1000290
2012-07-20  24.6499081
2012-07-23  23.9624634
2012-07-24  23.8560677
2012-07-25  23.5941849
2012-07-26  23.8642597
2012-07-27  24.3552933
2012-07-30  24.2570801
2012-07-31  24.1179543
2012-08-31 00:00:00
                  High         Low        Open       Close      Volume  \
Date
2012-08-01  29.6499996  29.2099991  29.5900002  29.4099998  31721800.0
2012-08-02  29.5300007  28.9699993  29.2099991  29.1900005  39520500.0
2012-08-03  29.9400005  29.4799995  29.5300007  29.7500000  35859400.0
2012-08-06  30.1100006  29.8099995  30.0000000  29.9500008  27471800.0
2012-08-07  30.3500004  29.8700008  30.0699997  30.2600002  28002900.0
2012-08-08  30.4699993  30.1100006  30.2099991  30.3299999  26257600.0
2012-08-09  30.6499996  30.2999992  30.3899994  30.5000000  24920800.0
2012-08-10  30.6200008  30.2500000  30.5000000  30.4200001  27810300.0
2012-08-13  30.4599991  30.1599998  30.3500004  30.3899994  23049100.0
2012-08-14  30.3899994  30.0100002  30.2999992  30.1299992  34551400.0
2012-08-15  30.2800007  30.0200005  30.1100006  30.2000008  24351000.0
2012-08-16  30.9400005  30.2600002  30.3600006  30.7800007  35787200.0
2012-08-17  30.9200001  30.5900002  30.9200001  30.8999996  32589900.0
2012-08-20  30.8500004  30.5799999  30.8199997  30.7399998  23737700.0
2012-08-21  30.9599991  30.6100006  30.7600002  30.7999992  28822700.0
2012-08-22  30.7600002  30.4699993  30.5900002  30.5400009  33437400.0
2012-08-23  30.3999996  30.0799999  30.3899994  30.2600002  28355600.0
2012-08-24  30.6299992  30.1800003  30.2500000  30.5599995  22943300.0
2012-08-27  30.9599991  30.5900002  30.9300003  30.6900005  34691100.0
2012-08-28  30.7999992  30.5200005  30.7000008  30.6299992  23947900.0
2012-08-29  30.7500000  30.4400005  30.6499996  30.6499996  23346800.0
2012-08-30  30.6100006  30.2199993  30.5300007  30.3199997  23982100.0
2012-08-31  30.9599991  30.3799992  30.6000004  30.8199997  36590100.0

             Adj Close
Date
2012-08-01  24.0688534
2012-08-02  23.8888092
2012-08-03  24.3471127
2012-08-06  24.5107899
2012-08-07  24.7644863
2012-08-08  24.8217716
2012-08-09  24.9608974
2012-08-10  24.8954353
2012-08-13  24.8708763
2012-08-14  24.8214493
2012-08-15  24.8791084
2012-08-16  25.3569279
2012-08-17  25.4557800
2012-08-20  25.3239727
2012-08-21  25.3733940
2012-08-22  25.1592140
2012-08-23  24.9285450
2012-08-24  25.1756821
2012-08-27  25.2827816
2012-08-28  25.2333527
2012-08-29  25.2498322
2012-08-30  24.9779720
2012-08-31  25.3898754
2012-09-30 00:00:00
                  High         Low        Open       Close       Volume  \
Date
2012-09-04  30.6599998  30.1499996  30.4500008  30.3899994   48556700.0
2012-09-05  30.5300007  30.2099991  30.2199993  30.3899994   33650000.0
2012-09-06  31.3600006  30.4599991  30.5000000  31.3500004   48371700.0
2012-09-07  31.0699997  30.7299995  31.0400009  30.9500008   42649100.0
2012-09-10  30.8999996  30.5100002  30.8299999  30.7199993   40524000.0
2012-09-11  30.9099998  30.6100006  30.6900005  30.7900009   25191800.0
2012-09-12  31.1800003  30.7299995  30.9400005  30.7800007   32775800.0
2012-09-13  31.1800003  30.3999996  30.8899994  30.9400005   45047300.0
2012-09-14  31.2500000  30.8099995  31.0100002  31.2099991   51422800.0
2012-09-17  31.2600002  31.0400009  31.1900005  31.2099991   36488500.0
2012-09-18  31.2099991  31.0300007  31.1000004  31.1800003   34542700.0
2012-09-19  31.1900005  31.0400009  31.0900002  31.0499992   48871900.0
2012-09-20  31.4799995  30.9099998  30.9500008  31.4500008   45543000.0
2012-09-21  31.6100006  31.0900002  31.4300003  31.1900005  102348900.0
2012-09-24  31.0699997  30.6399994  31.0000000  30.7800007   46825900.0
2012-09-25  31.0000000  30.3600006  30.9500008  30.3899994   54266400.0
2012-09-26  30.6000004  30.0400009  30.2800007  30.1700001   54672000.0
2012-09-27  30.3999996  29.8899994  30.1700001  30.1599998   47129900.0
2012-09-28  30.2600002  29.7399998  30.1800003  29.7600002   54229300.0

             Adj Close
Date
2012-09-04  25.0356388
2012-09-05  25.0356388
2012-09-06  25.8264942
2012-09-07  25.4969769
2012-09-10  25.3074951
2012-09-11  25.3651619
2012-09-12  25.3569279
2012-09-13  25.4887371
2012-09-14  25.7111645
2012-09-17  25.7111645
2012-09-18  25.6864491
2012-09-19  25.5793552
2012-09-20  25.9088802
2012-09-21  25.6946869
2012-09-24  25.3569279
2012-09-25  25.0356388
2012-09-26  24.8544064
2012-09-27  24.8461666
2012-09-28  24.5166397
2012-10-31 00:00:00
                  High         Low        Open       Close      Volume  \
Date
2012-10-01  29.9799995  29.4200001  29.8099995  29.4899998  54042700.0
2012-10-02  29.8899994  29.5000000  29.6800003  29.6599998  43338900.0
2012-10-03  29.9899998  29.6700001  29.7500000  29.8600006  46655900.0
2012-10-04  30.0300007  29.5699997  29.9699993  30.0300007  43634900.0
2012-10-05  30.2500000  29.7399998  30.2299995  29.8500004  41133900.0
2012-10-08  29.9200001  29.5499992  29.6399994  29.7800007  29752000.0
2012-10-09  29.7399998  29.1800003  29.6800003  29.2800007  45121100.0
2012-10-10  29.3099995  28.9500008  29.1499996  28.9799995  47227100.0
2012-10-11  29.2500000  28.8700008  29.2199993  28.9500008  41488500.0
2012-10-12  29.3199997  28.7999992  28.9699993  29.2000008  46464700.0
2012-10-15  29.7199993  29.2500000  29.3700008  29.5100002  42440200.0
2012-10-16  29.7399998  29.3199997  29.4500008  29.4899998  47739400.0
2012-10-17  29.6399994  29.0900002  29.2999992  29.5900002  44206100.0
2012-10-18  29.7299995  29.2600002  29.6499996  29.5000000  59238500.0

                  High         Low        Open       Close      Volume  \
Date
2013-05-01  33.0800018  32.5999985  32.9300003  32.7200012  54330900.0
2013-05-02  33.1699982  32.3899994  32.6300011  33.1599998  46059500.0
2013-05-03  33.5200005  33.0800018  33.2299995  33.4900017  46784600.0
2013-05-06  33.9099998  33.2500000  33.4199982  33.7500000  40978300.0
2013-05-07  33.7900009  33.2400017  33.6500015  33.3100014  43078300.0
2013-05-08  33.2400017  32.6500015  33.0699997  32.9900017  51595700.0
2013-05-09  33.0000000  32.5900002  32.8499985  32.6599998  46417800.0
2013-05-10  32.7200012  32.3199997  32.6699982  32.6899986  36394900.0
2013-05-13  33.0699997  32.5499992  32.6100006  33.0299988  36027600.0
2013-05-14  33.5299988  32.7999992  32.8600006  33.5299988  56870100.0
2013-05-15  33.9000015  33.4300003  33.4500008  33.8499985  46303900.0
2013-05-16  34.1500015  33.5499992  33.6399994  34.0800018  59382900.0
2013-05-17  34.8699989  34.0999985  34.1300011  34.8699989  60666700.0
2013-05-20  35.0999985  34.6800003  34.7299995  35.0800018  54020800.0
2013-05-21  35.2700005  34.7200012  35.0999985  34.8499985  48702400.0
2013-05-22  34.8400002  34.3600006  34.7900009  34.6100006  66047500.0
2013-05-23  34.5499992  33.9000015  34.2299995  34.1500015  51102700.0
2013-05-24  34.2799988  33.9000015  33.9199982  34.2700005  33174400.0
2013-05-28  35.1800003  34.4099998  34.4199982  35.0200005  48212100.0
2013-05-29  35.0200005  34.5699997  34.7400017  34.8800011  38412200.0
2013-05-30  35.2500000  34.8100014  34.8499985  35.0299988  51131000.0
2013-05-31  35.2799988  34.7900009  34.8199997  34.9000015  56165700.0

             Adj Close
Date
2013-05-01  27.4016209
2013-05-02  27.7700977
2013-05-03  28.0464611
2013-05-06  28.2642002
2013-05-07  27.8957233
2013-05-08  27.6277351
2013-05-09  27.3513756
2013-05-10  27.3764973
2013-05-13  27.6612339
2013-05-14  28.2768631
2013-05-15  28.5467224
2013-05-16  28.7406864
2013-05-17  29.4069214
2013-05-20  29.5840302
2013-05-21  29.3900585
2013-05-22  29.1876602
2013-05-23  28.7997303
2013-05-24  28.9009342
2013-05-28  29.5334187
2013-05-29  29.4153652
2013-05-30  29.5418606
2013-05-31  29.4322166
2013-06-30 00:00:00
                  High         Low        Open       Close      Volume  \
Date
2013-06-03  35.6300011  34.8300018  34.9199982  35.5900002  51252600.0
2013-06-04  35.7400017  34.7700005  35.6199989  34.9900017  65529500.0
2013-06-05  34.8899994  34.4300003  34.5999985  34.7799988  46025100.0
2013-06-06  35.1100006  34.4900017  34.8400002  34.9599991  37618500.0
2013-06-07  35.7799988  35.0600014  35.2500000  35.6699982  40757300.0
2013-06-10  35.6500015  35.1399994  35.5099983  35.4700012  35994500.0
2013-06-11  35.1800003  34.6800003  35.0499992  34.8400002  39435900.0
2013-06-12  35.2700005  34.8499985  35.1399994  35.0000000  37372700.0
2013-06-13  35.0200005  34.5900002  34.9900017  34.7200012  45654900.0
2013-06-14  34.6899986  34.2500000  34.5499992  34.4000015  53192600.0
2013-06-17  35.1599998  34.6300011  34.6899986  35.0000000  49670100.0
2013-06-18  35.1699982  34.9000015  34.9700012  34.9799995  28616500.0
2013-06-19  35.0900002  34.5900002  34.9599991  34.5900002  30816200.0
2013-06-20  34.3300018  33.3699989  34.2599983  33.4900017  54493700.0
2013-06-21  33.7299995  33.0499992  33.6599998  33.2700005  85338500.0
2013-06-24  34.2000008  32.5699997  32.9399986  33.7200012  56109000.0
2013-06-25  34.3800011  33.4599991  34.0800018  33.6699982  44073400.0
2013-06-26  34.4799995  33.8899994  34.1199989  34.3499985  48665900.0
2013-06-27  34.7799988  34.5000000  34.5200005  34.6199989  28993100.0
2013-06-28  34.7900009  34.3400002  34.3800011  34.5400009  65545500.0

             Adj Close
Date
2013-06-03  30.0141277
2013-06-04  29.5081348
2013-06-05  29.3310299
2013-06-06  29.4828205
2013-06-07  30.0815811
2013-06-10  29.9129200
2013-06-11  29.3816299
2013-06-12  29.5165558
2013-06-13  29.2804317
2013-06-14  29.0105629
2013-06-17  29.5165558
2013-06-18  29.4996929
2013-06-19  29.1707935
2013-06-20  28.2431278
2013-06-21  28.0575962
2013-06-24  28.4370937
2013-06-25  28.3949299
2013-06-26  28.9683876
2013-06-27  29.1960926
2013-06-28  29.1286221
2013-07-31 00:00:00
                  High         Low        Open       Close       Volume  \
Date
2013-07-01  34.9900017  34.3300018  34.7500000  34.3600006   31055400.0
2013-07-02  34.4399986  33.6300011  34.4099998  33.9399986   37630000.0
2013-07-03  34.3699989  33.5999985  33.6599998  34.0099983   15994400.0
2013-07-05  34.2400017  33.5800018  34.0900002  34.2099991   26085900.0
2013-07-08  34.5900002  33.9799995  34.3499985  34.3300018   32396900.0
2013-07-09  34.5999985  34.1399994  34.5800018  34.3499985   25318500.0
2013-07-10  34.8100014  34.3199997  34.3400002  34.7000008   29658800.0
2013-07-11  35.7700005  34.9000015  35.0000000  35.6899986   53638300.0
2013-07-12  35.7299995  35.2799988  35.5800018  35.6699982   35501200.0
2013-07-15  36.2200012  35.5800018  35.6599998  36.1699982   34142600.0
2013-07-16  36.4300003  35.9599991  36.0099983  36.2700005   36378500.0
2013-07-17  36.3899994  35.4900017  36.3400002  35.7400017   37285100.0
2013-07-18  35.8899994  35.2200012  35.7200012  35.4399986   49547100.0
2013-07-19  32.6699982  31.0200005  32.4000015  31.3999996  248428500.0
2013-07-22  32.0099983  31.6000004  31.7000008  32.0099983   79040700.0
2013-07-23  32.0400009  31.7099991  31.9099998  31.8199997   65810400.0
2013-07-24  32.1899986  31.8899994  32.0400009  31.9599991   52803100.0
2013-07-25  31.6499996  31.2500000  31.6200008  31.3899994   63213000.0
2013-07-26  31.6200008  31.2099991  31.2600002  31.6200008   38633600.0
2013-07-29  31.6000004  31.3999996  31.4699993  31.5400009   28870700.0
2013-07-30  32.1199989  31.5499992  31.7800007  31.8500004   45799500.0
2013-07-31  32.0499992  31.7099991  31.9699993  31.8400002   43898400.0

             Adj Close
Date
2013-07-01  28.9768219
2013-07-02  28.6226234
2013-07-03  28.6816673
2013-07-05  28.8503361
2013-07-08  28.9515305
2013-07-09  28.9683876
2013-07-10  29.2635555
2013-07-11  30.0984535
2013-07-12  30.0815811
2013-07-15  30.5032616
2013-07-16  30.5875835
2013-07-17  30.1406307
2013-07-18  29.8876324
2013-07-19  26.4805737
2013-07-22  26.9950008
2013-07-23  26.8347702
2013-07-24  26.9528351
2013-07-25  26.4721317
2013-07-26  26.6661053
2013-07-29  26.5986366
2013-07-30  26.8600693
2013-07-31  26.8516426
2013-08-31 00:00:00
                  High         Low        Open       Close       Volume  \
Date
2013-08-01  32.0900002  31.6000004  32.0600014  31.6700001   42557900.0
2013-08-02  31.8999996  31.5699997  31.6900005  31.8899994   29199900.0
2013-08-05  32.0000000  31.6399994  31.8999996  31.7000008   30984000.0
2013-08-06  31.6700001  31.3799992  31.5499992  31.5799999   36331500.0
2013-08-07  32.0999985  31.2500000  31.5400009  32.0600014   38078600.0
2013-08-08  33.0699997  32.0499992  32.2400017  32.8899994   59034400.0
2013-08-09  32.9000015  32.4700012  32.7700005  32.7000008   26800700.0
2013-08-12  32.9700012  32.4599991  32.4599991  32.8699989   25493700.0
2013-08-13  32.5499992  32.2099991  32.5099983  32.2299995   39464100.0
2013-08-14  33.3600006  31.7000008  32.1399994  32.3499985   48519600.0
2013-08-15  32.1800003  30.8400002  32.0000000  31.7900009   33338000.0
2013-08-16  31.9899998  31.6599998  31.7900009  31.7999992   32866300.0
2013-08-19  31.9699993  31.3799992  31.7600002  31.3899994   27902500.0
2013-08-20  31.8999996  31.3700008  31.4400005  31.6200008   22979600.0
2013-08-21  32.0099983  31.5400009  31.6100006  31.6100006   37409100.0
2013-08-22  32.4900017  32.0999985  32.1899986  32.3899994   31169900.0
2013-08-23  35.2000008  34.0000000  35.1699982  34.7500000  225493800.0
2013-08-26  34.6699982  34.0299988  34.4000015  34.1500015   72786800.0
2013-08-27  34.0999985  33.1500015  33.5200005  33.2599983   58522300.0
2013-08-28  33.5999985  33.0000000  33.3899994  33.0200005   44257400.0
2013-08-29  33.5999985  32.7999992  32.9300003  33.5499992   45284700.0
2013-08-30  33.4799995  33.0900002  33.3699989  33.4000015   42790200.0

             Adj Close
Date
2013-08-01  26.7082691
2013-08-02  26.8938007
2013-08-05  26.7335682
2013-08-06  26.6323662
2013-08-07  27.0371704
2013-08-08  27.7371330
2013-08-09  27.5769024
2013-08-12  27.7202663
2013-08-13  27.3720627
2013-08-14  27.4739799
2013-08-15  26.9983845
2013-08-16  27.0068836
2013-08-19  26.6586704
2013-08-20  26.8540115
2013-08-21  26.8455124
2013-08-22  27.5079441
2013-08-23  29.5122318
2013-08-26  29.0026722
2013-08-27  28.2468128
2013-08-28  28.0429916
2013-08-29  28.4931011
2013-08-30  28.3657169
2013-09-30 00:00:00
                  High         Low        Open       Close       Volume  \
Date
2013-09-03  32.0699997  31.2900009  31.7500000  31.8799992  154507000.0
2013-09-04  31.4699993  31.1100006  31.3899994  31.2000008  142320600.0
2013-09-05  31.4400005  30.9500008  31.1000004  31.2299995   71644900.0
2013-09-06  31.3899994  31.1299992  31.3099995  31.1499996   75434900.0
2013-09-09  31.7900009  31.2000008  31.2199993  31.6599998   49628500.0
2013-09-10  32.4000015  31.7900009  31.8999996  32.3899994   56881200.0
2013-09-11  32.9300003  32.5299988  32.5699997  32.7400017   39087500.0
2013-09-12  32.7799988  32.5900002  32.7200012  32.6899986   32860200.0
2013-09-13  33.0699997  32.5099983  32.7700005  33.0299988   40899000.0
2013-09-16  33.5000000  32.7299995  33.3800011  32.7999992   52839700.0
2013-09-17  33.4700012  32.9000015  33.4199982  32.9300003   84716500.0
2013-09-18  33.4000015  32.8300018  32.9900017  33.3199997   64099900.0
2013-09-19  33.6800003  33.3199997  33.4799995  33.6399994   42026600.0
2013-09-20  33.4799995  32.6899986  33.4099998  32.7900009  102904900.0
2013-09-23  32.9700012  32.5000000  32.5400009  32.7400017   39826100.0
2013-09-24  32.8699989  32.1500015  32.8699989  32.4500008   40685000.0
2013-09-25  32.7999992  32.4000015  32.4900017  32.5099983   28907500.0
2013-09-26  33.0000000  32.5900002  32.6399994  32.7700005   28504000.0
2013-09-27  33.7500000  32.8699989  32.8800011  33.2700005   55348000.0
2013-09-30  33.3100014  32.7000008  33.0000000  33.2799988   39839500.0

             Adj Close
Date
2013-09-03  27.0748234
2013-09-04  26.4973145
2013-09-05  26.5227928
2013-09-06  26.4548531
2013-09-09  26.8879833
2013-09-10  27.5079441
2013-09-11  27.8051949
2013-09-12  27.7627335
2013-09-13  28.0514832
2013-09-16  27.8561535
2013-09-17  27.9665585
2013-09-18  28.2977753
2013-09-19  28.5695343
2013-09-20  27.8476601
2013-09-23  27.8051949
2013-09-24  27.5589046
2013-09-25  27.6098557
2013-09-26  27.8306713
2013-09-27  28.2553043
2013-09-30  28.2638054
2013-10-31 00:00:00
                  High         Low        Open       Close       Volume  \
Date
2013-10-01  33.6100006  33.2999992  33.3499985  33.5800018   36718700.0
2013-10-02  34.0299988  33.2900009  33.3600006  33.9199982   46946800.0
2013-10-03  34.0000000  33.4199982  33.8800011  33.8600006   38703800.0
2013-10-04  33.9900017  33.6199989  33.6899986  33.8800011   33008100.0
2013-10-07  33.7099991  33.2000008  33.5999985  33.2999992   35069300.0
2013-10-08  33.3300018  32.7999992  33.3100014  33.0099983   41017600.0
2013-10-09  33.3499985  32.9599991  33.0699997  33.0699997   35878600.0
2013-10-10  33.8899994  33.2599983  33.3100014  33.7599983   42875100.0
2013-10-11  34.1399994  33.6800003  33.6800003  34.1300011   30033300.0
2013-10-14  34.5000000  33.7799988  33.9000015  34.4500008   27757900.0
2013-10-15  34.9900017  34.4700012  34.6699982  34.4900017   47097800.0
2013-10-16  34.9000015  34.5600014  34.5999985  34.6399994   35111600.0
2013-10-17  34.9900017  34.3699989  34.4500008  34.9199982   31359200.0
2013-10-18  34.9900017  34.3300018  34.8199997  34.9599991   41811700.0
2013-10-21  35.2000008  34.9099998  34.9799995  34.9900017   27433500.0
2013-10-22  35.0999985  34.5200005  35.0200005  34.5800018   40438500.0
2013-10-23  34.4900017  33.6699982  34.3499985  33.7599983   58600500.0
2013-10-24  34.0999985  33.5699997  33.8199997  33.7200012   53209700.0
2013-10-25  36.2900009  35.4700012  35.8800011  35.7299995  113494000.0
2013-10-28  35.7299995  35.2700005  35.6100006  35.5699997   38383600.0
2013-10-29  35.7200012  35.2599983  35.6300011  35.5200005   31702200.0
2013-10-30  35.7900009  35.4300003  35.5299988  35.5400009   36997700.0
2013-10-31  35.6899986  35.3400002  35.6599998  35.4099998   41682300.0

             Adj Close
Date
2013-10-01  28.5185890
2013-10-02  28.8073311
2013-10-03  28.7563801
2013-10-04  28.7733650
2013-10-07  28.2807865
2013-10-08  28.0344944
2013-10-09  28.0854588
2013-10-10  28.6714535
2013-10-11  28.9856873
2013-10-14  29.2574520
2013-10-15  29.2914162
2013-10-16  29.4188080
2013-10-17  29.6566067
2013-10-18  29.6905727
2013-10-21  29.7160645
2013-10-22  29.3678646
2013-10-23  28.6714535
2013-10-24  28.6374779
2013-10-25  30.3445168
2013-10-28  30.2086353
2013-10-29  30.1661835
2013-10-30  30.1831608
2013-10-31  30.0727520
2013-11-30 00:00:00
                  High         Low        Open       Close      Volume  \
Date
2013-11-01  35.6899986  35.3899994  35.6699982  35.5299988  40264600.0
2013-11-04  35.9799995  35.5499992  35.5900002  35.9399986  28060700.0
2013-11-05  36.7099991  35.7700005  35.7900009  36.6399994  51681900.0
2013-11-06  38.2200012  37.0600014  37.2400017  38.1800003  88948800.0
2013-11-07  38.0099983  37.4300003  37.9599991  37.5000000  60437400.0
2013-11-08  37.7799988  37.3400002  37.6699982  37.7799988  36737800.0
2013-11-11  37.7799988  37.3499985  37.6899986  37.5900002  26872500.0
2013-11-12  37.5999985  37.2000008  37.3800011  37.3600006  31651600.0
2013-11-13  38.1599998  36.9000015  36.9799995  38.1599998  44957600.0
2013-11-14  38.1300011  37.7200012  37.8699989  38.0200005  46183700.0
2013-11-15  38.0200005  37.7200012  37.9500008  37.8400002  50601300.0
2013-11-18  37.5800018  37.0699997  37.3499985  37.2000008  53277500.0
2013-11-19  37.2299995  36.6699982  36.8499985  36.7400017  44275000.0
2013-11-20  37.4099998  36.8600006  36.9199982  37.0800018  32229900.0
2013-11-21  37.5299988  37.2599983  37.2700005  37.4000015  23064700.0
2013-11-22  37.6800003  37.3300018  37.5299988  37.5699997  27982000.0
2013-11-25  37.9500008  37.5699997  37.9300003  37.6399994  30646800.0
2013-11-26  37.6500015  37.3499985  37.5699997  37.3499985  34465300.0
2013-11-27  37.7599983  37.4900017  37.5699997  37.5999985  26002100.0
2013-11-29  38.2900009  37.8199997  37.8199997  38.1300011  22090400.0

             Adj Close
Date
2013-11-01  30.1746616
2013-11-04  30.5228691
2013-11-05  31.1173668
2013-11-06  32.4252472
2013-11-07  31.8477364
2013-11-08  32.0855293
2013-11-11  31.9241600
2013-11-12  31.7288513
2013-11-13  32.4082565
2013-11-14  32.2893562
2013-11-15  32.1364822
2013-11-18  31.5929508
2013-11-19  31.4389210
2013-11-20  31.7298622
2013-11-21  32.0036888
2013-11-22  32.1491661
2013-11-25  32.2090683
2013-11-26  31.9609032
2013-11-27  32.1748276
2013-11-29  32.6283684
2013-12-31 00:00:00
                  High         Low        Open       Close       Volume  \
Date
2013-12-02  38.7799988  38.0600014  38.0900002  38.4500008   42950400.0
2013-12-03  38.4900017  38.0800018  38.1399994  38.3100014   52109800.0
2013-12-04  38.9799995  38.1199989  38.2099991  38.9399986   51983600.0
2013-12-05  38.8800011  37.1800003  38.8499985  38.0000000  116305000.0
2013-12-06  38.5499992  37.9900017  38.4199982  38.3600006   36457300.0
2013-12-09  38.8699989  38.3699989  38.5600014  38.7099991   30286000.0
2013-12-10  38.9000015  38.0200005  38.6100006  38.1100006   37828600.0
2013-12-11  38.2999992  37.3899994  38.0600014  37.6100006   39853400.0
2013-12-12  37.6399994  37.1800003  37.6399994  37.2200012   36012800.0
2013-12-13  37.4500008  36.6199989  37.4199982  36.6899986   40066100.0
2013-12-16  37.0000000  36.5400009  36.7299995  36.8899994   31734200.0
2013-12-17  37.1100006  36.3300018  36.9399986  36.5200005   45687700.0
2013-12-18  36.5999985  35.5299988  36.3600006  36.5800018   63192100.0
2013-12-19  36.5499992  36.0800018  36.5099983  36.2500000   34160100.0
2013-12-20  36.9300003  36.1899986  36.2000008  36.7999992   62649100.0
2013-12-23  36.8899994  36.5499992  36.8100014  36.6199989   25128700.0
2013-12-24  37.1699982  36.6399994  36.7200012  37.0800018   14243000.0
2013-12-26  37.4900017  37.1699982  37.2000008  37.4399986   17612800.0
2013-12-27  37.6199989  37.1699982  37.5800018  37.2900009   14563000.0
2013-12-30  37.3800011  36.9000015  37.2200012  37.2900009   16290500.0

             Adj Close
Date
2013-12-02  32.9021988
2013-12-03  32.7823906
2013-12-04  33.3214874
2013-12-05  32.5171204
2013-12-06  32.8251648
2013-12-09  33.1246681
2013-12-10  32.6112518
2013-12-11  32.1833916
2013-12-12  31.8496532
2013-12-13  31.3961525
2013-12-16  31.5672779
2013-12-17  31.2506657
2013-12-18  31.3020077
2013-12-19  31.0196228
2013-12-20  31.4902725
2013-12-23  31.3362408
2013-12-24  31.7298622
2013-12-26  32.0379295
2013-12-27  31.9095631
2013-12-30  31.9095631

In [57]:
msft_resample.mean()
# mean of high, low, open, close, volume and adj close for each month.

,High,Low,Open,Close,Volume,Adj Close
Date,,,,,,
2012-01-31,28.6900001,28.1710001,28.3479999,28.5165000,6.7742905e+07,23.0338481
2012-02-29,30.9949998,30.5429999,30.7125000,30.8250002,4.9216615e+07,24.9898028
2012-03-31,32.3877273,31.9777278,32.1986364,32.1949996,4.2834841e+07,26.1763098
2012-04-30,31.7935000,31.2899999,31.5374999,31.5054999,4.7036985e+07,25.6157076
2012-05-31,30.5136363,29.9890909,30.2831819,30.2263634,4.6107845e+07,24.6615313
2012-06-30,29.9628571,29.3761903,29.7085713,29.6804763,4.6339590e+07,24.2902100
2012-07-31,30.0261905,29.4404762,29.8138094,29.7571428,4.0314481e+07,24.3529515
2012-08-31,30.5213043,30.1352173,30.3373913,30.3573913,2.9206452e+07,24.9450835
2012-09-30,31.0063158,30.5468421,30.7847371,30.7821053,4.7005668e+07,25.3586605
2012-10-31,29.3447618,28.8728572,29.1514284,29.0661905,5.2638205e+07,23.9450689
2012-11-30,28.1100000,27.6004760,27.8914286,27.8119048,6.2405529e+07,23.0247895
2012-12-31,27.1934999,26.7345001,26.9910001,26.9659999,4.7365545e+07,22.3974513
2013-01-31,27.4914285,27.0261904,27.2433334,27.2366666,5.4526400e+07,22.6222628
2013-02-28,27.8963157,27.5257894,27.7231578,27.7042107,4.1083526e+07,23.0907718
2013-03-31,28.2630001,27.9340000,28.0875001,28.1410002,4.2247300e+07,23.5669028
2013-04-30,30.0877274,29.4577275,29.6422727,29.8709093,6.6625327e+07,25.0156271
2013-05-31,34.1236364,33.5768185,33.7609088,33.9509094,4.8720909e+07,28.5523370
2013-06-30,34.9535002,34.3195002,34.6524996,34.6325001,4.7257775e+07,29.2066343
2013-07-31,33.9281816,33.3340910,33.6654548,33.6504542,5.0505936e+07,28.3784468
2013-08-31,32.8090906,32.1495453,32.4740909,32.4850000,4.7784773e+07,27.5191115
2013-09-30,32.7785002,32.2390002,32.4915001,32.5234999,6.2148075e+07,27.6213270
2013-10-31,34.6317394,34.1078259,34.3552173,34.3821740,4.1970935e+07,29.1998483
2013-11-30,37.5579998,37.0425001,37.2299995,37.3625000,4.0021580e+07,31.8274137
2013-12-31,37.7789999,37.1055000,37.5135000,37.4580002,4.0455710e+07,32.0533242

In [58]:
msft.loc['1/2012', 'Adj Close'].mean()
# confirmed that 'msft_resample.mean()' has produced mean of high, low, open, close, volume and adj close for each month.

23.033848094940186